## Случайный лес

### 0. Выбор датасета:

Выбор пал на предложенный авторами задания датасет - https://www.kaggle.com/datasets/vishakhdapat/price-of-used-toyota-corolla-cars

Его название - ToyotaCorolla.

Колонки выбранного датасета:
- Id (айдишка);
- Model (модель автомобиля);
- Price (цена (в будущем будет target));
- Age_08_04 (возраст автомобиля);
- Mfg_Month (месяц производства);
- Mfg_Year (год производства);
- KM (пробег автомобиля);
- Fuel_Type (вид топлива);
- HP (мощность автомобиля);
- Met_Color (металлик: 1 — да, 0 — нет);
- Color (цвет автомобиля);
- Automatic (АКПП: 1 — да, 0 — нет);
- CC (объем двигателя);
- Doors (количество дверей автомобиля);
- Cylinders (количество цилиндров двигателя автомобиля);
- Gears (количество передач КПП);
- Quarterly_Tax (налог на автомобиль);
- Weight (вес автомобиля);
- Mfr_Guarantee (гарантия от производителя: 1 — да, 0 — нет);
- BOVAG_Guarantee (гарантия BOVAG: 1 — да, 0 — нет);
- Guarantee_Period (срок гарантии);
- ABS (антиблокировочная система: 1 — есть, 0 — нет);
- Airbag_1 (подушка безопасности водителя: 1 — есть, 0 — нет);
- Airbag_2 (подушка безопасности пассажира: 1 — есть, 0 — нет);
- Airco (кондиционер: 1 — есть, 0 — нет);
- Automatic_airco (климат-контроль: 1 — есть, 0 — нет);
- Boardcomputer (бортовой компьютер: 1 — есть, 0 — нет);
- CD_Player (CD-плеер: 1 — есть, 0 — нет);
- Central_Lock (центральный замок: 1 — есть, 0 — нет);
- Powered_Windows (электростеклоподъемники: 1 — есть, 0 — нет);
- Power_Steering (усилитель руля: 1 — есть, 0 — нет);
- Radio (радио: 1 — есть, 0 — нет);
- Mistlamps (противотуманные фары: 1 — есть, 0 — нет);
- Sport_Model (спортивная комплектация: 1 — да, 0 — нет);
- Backseat_Divider (подлокотник задних сидений: 1 — есть, 0 — нет);
- Metallic_Rim (легкосплавные диски: 1 — есть, 0 — нет);
- Radio_cassette (радиокассетная магнитола: 1 — есть, 0 — нет);
- Parking_Assistant (парктроник: 1 — есть, 0 — нет);
- Tow_Bar (фаркоп: 1 — есть, 0 — нет);

Я выбрал данный датасет, потому что:
- так написано в условии задания

### 1. Разделение выборки

Это, конечно, круто, но давайте сначала скопируем eda из 4-й домашки.

In [21]:
import time
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from plotly import express as px
from sklearn.preprocessing import OneHotEncoder
from category_encoders import TargetEncoder
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor
from sklearn.model_selection import train_test_split, GridSearchCV, RandomizedSearchCV
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
sns.set_style('dark')

df = pd.read_csv('ToyotaCorolla.csv')
df.drop('Id', axis=1, inplace=True)

In [22]:
df.shape

(1436, 38)

In [23]:
df.head(2)

,Model,Price,Age_08_04,Mfg_Month,Mfg_Year,KM,Fuel_Type,HP,Met_Color,Color,...,Powered_Windows,Power_Steering,Radio,Mistlamps,Sport_Model,Backseat_Divider,Metallic_Rim,Radio_cassette,Parking_Assistant,Tow_Bar
0,TOYOTA Corolla 2.0 D4D HATCHB TERRA 2/3-Doors,13500,23,10,2002,46986,Diesel,90,1,Blue,...,1,1,0,0,0,1,0,0,0,0
1,TOYOTA Corolla 2.0 D4D HATCHB TERRA 2/3-Doors,13750,23,10,2002,72937,Diesel,90,1,Silver,...,0,1,0,0,0,1,0,0,0,0

In [24]:
df.tail(2)

,Model,Price,Age_08_04,Mfg_Month,Mfg_Year,KM,Fuel_Type,HP,Met_Color,Color,...,Powered_Windows,Power_Steering,Radio,Mistlamps,Sport_Model,Backseat_Divider,Metallic_Rim,Radio_cassette,Parking_Assistant,Tow_Bar
1434,TOYOTA Corolla 1.3 16V HATCHB LINEA TERRA 2/3-...,7250,70,11,1998,16916,Petrol,86,1,Grey,...,0,0,0,0,0,1,0,0,0,0
1435,TOYOTA Corolla 1.6 LB LINEA TERRA 4/5-Doors,6950,76,5,1998,1,Petrol,110,0,Green,...,0,1,0,0,0,0,0,0,0,0

In [25]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1436 entries, 0 to 1435
Data columns (total 38 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Model              1436 non-null   str
 1   Price              1436 non-null   int64
 2   Age_08_04          1436 non-null   int64
 3   Mfg_Month          1436 non-null   int64
 4   Mfg_Year           1436 non-null   int64
 5   KM                 1436 non-null   int64
 6   Fuel_Type          1436 non-null   str
 7   HP                 1436 non-null   int64
 8   Met_Color          1436 non-null   int64
 9   Color              1436 non-null   str
 10  Automatic          1436 non-null   int64
 11  CC                 1436 non-null   int64
 12  Doors              1436 non-null   int64
 13  Cylinders          1436 non-null   int64
 14  Gears              1436 non-null   int64
 15  Quarterly_Tax      1436 non-null   int64
 16  Weight             1436 non-null   int64
 17  Mfr_Guarantee      1436 non-null   int64
 18  BOVAG_Guarantee    1436 non-null   int64
 19  Guarantee_Period   1436 non-null   int64
 20  ABS                1436 non-null   int64
 21  Airbag_1           1436 non-null   int64
 22  Airbag_2           1436 non-null   int64
 23  Airco              1436 non-null   int64
 24  Automatic_airco    1436 non-null   int64
 25  Boardcomputer      1436 non-null   int64
 26  CD_Player          1436 non-null   int64
 27  Central_Lock       1436 non-null   int64
 28  Powered_Windows    1436 non-null   int64
 29  Power_Steering     1436 non-null   int64
 30  Radio              1436 non-null   int64
 31  Mistlamps          1436 non-null   int64
 32  Sport_Model        1436 non-null   int64
 33  Backseat_Divider   1436 non-null   int64
 34  Metallic_Rim       1436 non-null   int64
 35  Radio_cassette     1436 non-null   int64
 36  Parking_Assistant  1436 non-null   int64
 37  Tow_Bar            1436 non-null   int64
dtypes: int64(35), str(3)
memory usage: 426.4 KB

In [26]:
df.describe()

,Price,Age_08_04,Mfg_Month,Mfg_Year,KM,HP,Met_Color,Automatic,CC,Doors,...,Powered_Windows,Power_Steering,Radio,Mistlamps,Sport_Model,Backseat_Divider,Metallic_Rim,Radio_cassette,Parking_Assistant,Tow_Bar
count,1436.000000,1436.000000,1436.000000,1436.000000,1436.000000,1436.000000,1436.000000,1436.000000,1436.00000,1436.000000,...,1436.000000,1436.000000,1436.000000,1436.000000,1436.000000,1436.000000,1436.000000,1436.000000,1436.000000,1436.000000
mean,10730.824513,55.947075,5.548747,1999.625348,68533.259749,101.502089,0.674791,0.055710,1576.85585,4.033426,...,0.561978,0.977716,0.146240,0.256964,0.300139,0.770195,0.204735,0.145543,0.002786,0.277855
std,3626.964585,18.599988,3.354085,1.540722,37506.448872,14.981080,0.468616,0.229441,424.38677,0.952677,...,0.496317,0.147657,0.353469,0.437111,0.458478,0.420854,0.403649,0.352770,0.052723,0.448098
min,4350.000000,1.000000,1.000000,1998.000000,1.000000,69.000000,0.000000,0.000000,1300.00000,2.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,8450.000000,44.000000,3.000000,1998.000000,43000.000000,90.000000,0.000000,0.000000,1400.00000,3.000000,...,0.000000,1.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000
50%,9900.000000,61.000000,5.000000,1999.000000,63389.500000,110.000000,1.000000,0.000000,1600.00000,4.000000,...,1.000000,1.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000
75%,11950.000000,70.000000,8.000000,2001.000000,87020.750000,110.000000,1.000000,0.000000,1600.00000,5.000000,...,1.000000,1.000000,0.000000,1.000000,1.000000,1.000000,0.000000,0.000000,0.000000,1.000000
max,32500.000000,80.000000,12.000000,2004.000000,243000.000000,192.000000,1.000000,1.000000,16000.00000,5.000000,...,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000

In [27]:
df.isnull().sum()

Model                0
Price                0
Age_08_04            0
Mfg_Month            0
Mfg_Year             0
KM                   0
Fuel_Type            0
HP                   0
Met_Color            0
Color                0
Automatic            0
CC                   0
Doors                0
Cylinders            0
Gears                0
Quarterly_Tax        0
Weight               0
Mfr_Guarantee        0
BOVAG_Guarantee      0
Guarantee_Period     0
ABS                  0
Airbag_1             0
Airbag_2             0
Airco                0
Automatic_airco      0
Boardcomputer        0
CD_Player            0
Central_Lock         0
Powered_Windows      0
Power_Steering       0
Radio                0
Mistlamps            0
Sport_Model          0
Backseat_Divider     0
Metallic_Rim         0
Radio_cassette       0
Parking_Assistant    0
Tow_Bar              0
dtype: int64

In [28]:
print(df.select_dtypes(include=['int64', 'float64']).var())
print(df.select_dtypes(include=['int64', 'float64']).skew())
print(df.select_dtypes(include=['int64', 'float64']).kurtosis())

Price                1.315487e+07
Age_08_04            3.459596e+02
Mfg_Month            1.124989e+01
Mfg_Year             2.373824e+00
KM                   1.406734e+09
HP                   2.244327e+02
Met_Color            2.196010e-01
Automatic            5.264333e-02
CC                   1.801041e+05
Doors                9.075927e-01
Cylinders            0.000000e+00
Gears                3.553619e-02
Quarterly_Tax        1.691563e+03
Weight               2.771088e+03
Mfr_Guarantee        2.419730e-01
BOVAG_Guarantee      9.361078e-02
Guarantee_Period     9.066270e+00
ABS                  1.519047e-01
Airbag_1             2.841226e-02
Airbag_2             2.004814e-01
Airco                2.501043e-01
Automatic_airco      5.326206e-02
Boardcomputer        2.079426e-01
CD_Player            1.709685e-01
Central_Lock         2.437564e-01
Powered_Windows      2.463303e-01
Power_Steering       2.180272e-02
Radio                1.249406e-01
Mistlamps            1.910665e-01
Sport_Model          2.102021e-01
Backseat_Divider     1.771180e-01
Metallic_Rim         1.629323e-01
Radio_cassette       1.244470e-01
Parking_Assistant    2.779692e-03
Tow_Bar              2.007915e-01
dtype: float64
Price                 1.703885
Age_08_04            -0.826702
Mfg_Month             0.290661
Mfg_Year              0.911304
KM                    1.015912
HP                    0.955836
Met_Color            -0.747029
Automatic             3.878197
CC                   27.431793
Doors                -0.076395
Cylinders             0.000000
Gears                 2.283960
Quarterly_Tax         1.993834
Weight                3.108639
Mfr_Guarantee         0.368588
BOVAG_Guarantee      -2.589204
Guarantee_Period      5.838435
ABS                  -1.610303
Airbag_1             -5.593385
Airbag_2             -0.996767
Airco                -0.033466
Automatic_airco       3.849562
Boardcomputer         0.902259
CD_Player             1.362712
Central_Lock         -0.324863
Powered_Windows      -0.250099
Power_Steering       -6.479621
Radio                 2.004439
Mistlamps             1.113561
Sport_Model           0.873060
Backseat_Divider     -1.285823
Metallic_Rim          1.465019
Radio_cassette        2.012363
Parking_Assistant    18.887772
Tow_Bar               0.992885
dtype: float64
Price                  3.737781
Age_08_04             -0.076632
Mfg_Month             -1.053692
Mfg_Year               0.070573
KM                     1.685057
HP                     8.836434
Met_Color             -1.443961
Automatic             13.058597
CC                   930.711227
Doors                 -1.874765
Cylinders              0.000000
Gears                 37.703476
Quarterly_Tax          4.298345
Weight                19.362901
Mfr_Guarantee         -1.866745
BOVAG_Guarantee        4.710535
Guarantee_Period      45.895434
ABS                    0.593902
Airbag_1              29.326794
Airbag_2              -1.007861
Airco                 -2.001670
Automatic_airco       12.837003
Boardcomputer         -1.187585
CD_Player             -0.143217
Central_Lock          -1.897108
Powered_Windows       -1.940155
Power_Steering        40.041251
Radio                  2.020588
Mistlamps             -0.761044
Sport_Model           -1.239494
Backseat_Divider      -0.347145
Metallic_Rim           0.146482
Radio_cassette         2.052462
Parking_Assistant    355.242681
Tow_Bar               -1.015596
dtype: float64

График boxplot для всех числовых признаков:

In [29]:
df_melted = df.select_dtypes(include=['int64', 'float64']).melt(var_name='Attribute', value_name='Value')
fig = px.box(
    df_melted,
    x='Attribute',
    y='Value',
    template='plotly_dark'
)

fig.show()

Теперь построим графики распределения по средней цене для признаков: модель, цвет, вид топлива.

In [30]:
df_cols_cat = df.select_dtypes(include='str').columns.to_list()
for i in df_cols_cat:
    fig = px.histogram(
        df,
        x=i,
        y='Price',
        height=500,
        width=800,
        histfunc='avg',
        nbins=50
    )
    fig.update_layout(
        yaxis_title='Average price'
    )
    fig.update_traces(
        marker_line_color='black',
        marker_line_width=0.5
    )
    fig.show()

Перейдём непосредственно к разбиению данных, но перед этим ответим на вопросы:

Сделали ли вы предобработку данных для случайного леса? Отличалась ли она от предобработки данных для линейной модели? Если до, то почему?
- не отличалась, ибо eda за редким исключением почти одинаковый для всех моделей;

Как именно вы разделили выборку?
- ниже увидим, что аналогично лин. регрессии: train 80%, test 20%;

На сколько частей нужно делить выборку при использовании кросс-валидации?
- хз, я всегда пишу cv=5, это оптимально вроде как;

Можно ли не использовать кросс-валидацию? Если да, то как делить выборку в таком случае?
- добавлять val и на нём считать гиперпараметры, но это и сложно, и неэффективно (подойдёт только чтобы лучше узнать, как под капотом работает GridSearchCV);

In [31]:
y = df.Price
X = df.drop('Price', axis=1)
X_train, X_test, y_train, y_test = train_test_split(
    X, y, random_state=42, test_size=0.2
)

Теперь применим encoding:

In [32]:
categorical_cols = X.select_dtypes(include='object').columns.to_list()

target_cols = ['Model']
onehot_cols = ['Color', 'Fuel_Type']

preprocessor = ColumnTransformer([
    ('target', TargetEncoder(smoothing=10), target_cols),
    ('onehot', OneHotEncoder(handle_unknown='ignore', sparse_output=False), onehot_cols)
], remainder='passthrough')

C:\Users\Пользователь\AppData\Local\Temp\ipykernel_12836\1942158160.py:1: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  categorical_cols = X.select_dtypes(include='object').columns.to_list()

### 2. Обучение моделей

Продолжаем обучение тут: строим Pipeline, вызываем GridSearchCV, отдельно учим модель с одним деревом, после - отвечаем на вопросы.

In [33]:
pipeline = Pipeline([
    ('preprocessor', preprocessor),
    ('rf', RandomForestRegressor(random_state=42))
])

m = X.shape[1]

param_grid = {
    'rf__n_estimators': [100, 200, 400],
    'rf__max_depth': [10, 30, 50, 100],
    'rf__min_samples_split': [2, 5],
    'rf__min_samples_leaf': [1, 4, 10, 20, 50],
    'rf__max_features': ['sqrt', 'log2', int(m/3)]
} # хотел бы больше, но мой ноут плачет от боли

grid_search = RandomizedSearchCV(
    pipeline,
    param_grid,
    n_iter=50,
    cv=5, n_jobs=-1, scoring='r2'
)

grid_search.fit(X_train, y_train)

RandomizedSearchCV(cv=5,
                   estimator=Pipeline(steps=[('preprocessor',
                                              ColumnTransformer(remainder='passthrough',
                                                                transformers=[('target',
                                                                               TargetEncoder(),
                                                                               ['Model']),
                                                                              ('onehot',
                                                                               OneHotEncoder(handle_unknown='ignore',
                                                                                             sparse_output=False),
                                                                               ['Color',
                                                                                'Fuel_Type'])])),
                                             ('rf',
                                              RandomForestRegressor(random_state=42))]),
                   n_iter=50, n_jobs=-1,
                   param_distributions={'rf__max_depth': [10, 30, 50, 100],
                                        'rf__max_features': ['sqrt', 'log2',
                                                             12],
                                        'rf__min_samples_leaf': [1, 4, 10, 20,
                                                                 50],
                                        'rf__min_samples_split': [2, 5],
                                        'rf__n_estimators': [100, 200, 400]},
                   scoring='r2')

In [34]:
print(f"Лучшие параметры: {grid_search.best_params_}")
print(f"Лучший R2 на CV: {grid_search.best_score_}")

rf_model = grid_search.best_estimator_

Лучшие параметры: {'rf__n_estimators': 400, 'rf__min_samples_split': 2, 'rf__min_samples_leaf': 1, 'rf__max_features': 'sqrt', 'rf__max_depth': 50}
Лучший R2 на CV: 0.8634208864365206

Победила модель с 400 деревьями, макс. глубиной - 30 (соответствует теории: большие деревья).

Интересно, что число признаков - sqrt(m) справилось лучше, чем m/3 (не соотв. теории).

Теперь обучим одно дерево с макс. глубиной 100 и посмотрим, как справится оно:

In [39]:
pipeline_tree = Pipeline([
    ('preprocessor', preprocessor),
    ('tree', DecisionTreeRegressor(random_state=42))
])

param_grid_tree = {
    'tree__max_depth': [50],
    'tree__min_samples_split': [2, 5, 10, 20],
    'tree__min_samples_leaf': [1, 4, 10, 20],
}

grid_search_tree = GridSearchCV(
    pipeline_tree,
    param_grid_tree, 
    cv=5, n_jobs=-1, scoring='r2'
)

grid_search_tree.fit(X_train, y_train)

GridSearchCV(cv=5,
             estimator=Pipeline(steps=[('preprocessor',
                                        ColumnTransformer(remainder='passthrough',
                                                          transformers=[('target',
                                                                         TargetEncoder(),
                                                                         ['Model']),
                                                                        ('onehot',
                                                                         OneHotEncoder(handle_unknown='ignore',
                                                                                       sparse_output=False),
                                                                         ['Color',
                                                                          'Fuel_Type'])])),
                                       ('tree',
                                        DecisionTreeRegressor(random_state=42))]),
             n_jobs=-1,
             param_grid={'tree__max_depth': [50],
                         'tree__min_samples_leaf': [1, 4, 10, 20],
                         'tree__min_samples_split': [2, 5, 10, 20]},
             scoring='r2')

In [45]:
print(f"Лучшие параметры дерева: {grid_search_tree.best_params_}")
print(f"Лучший R² на CV: {grid_search_tree.best_score_:.4f}")

Лучшие параметры дерева: {'tree__max_depth': 50, 'tree__min_samples_leaf': 20, 'tree__min_samples_split': 2}
Лучший R² на CV: 0.7391

### Ответы на вопросы:

Обучите случайный лес. Обучите одно дерево той же глубины, какую вы укажете в случайном лесе. Сравните результаты.

Сравнение скорости: сравните, какая модель обучалась быстрее. 
- очевидно, одно дерево обучилось быстрее, причина - отсутствие гиперпараметра на кол-во деревьев и, как следствие, лучшее алгоритмическое время на обучение;

Можно ли добиться одинаковой или близкой к одинаковой скорости?
- может и можно, но я хз как (вряд ли);

Сравнение качества: сравните результаты одного дерева и случайного леса. 
- одно дерево слабее сильно (0.74 r2 - никуда не годится, слабая модель) в сравнении с лесом (0.86 r2);

Теперь, оценив качество обучения модели на Train, для дальнейшего сравнения с linear regression посмотрим результат r2 и других метрик на test выборке.

In [42]:
def mape(y_true, y_pred):
    return np.mean(np.abs((y_true - y_pred) / y_true)) * 100

In [46]:
y_pred = rf_model.predict(X_test)

print("=== Метрики модели случайный лес===")
print(f"Test  R²: {r2_score(y_test, y_pred):.4f}")
print(f"Test  MAE: {mean_absolute_error(y_test, y_pred):.0f}")
print(f"Test  RMSE: {np.sqrt(mean_squared_error(y_test, y_pred)):.0f}")
print(f"Test  MAPE: {mape(y_test, y_pred):.2f}%")
print(f"Test MSE: {mean_squared_error(y_test, y_pred)}")

=== Метрики модели случайный лес===
Test  R²: 0.9050
Test  MAE: 820
Test  RMSE: 1126
Test  MAPE: 8.40%
Test MSE: 1267954.0236055006

### 3. Оценка качества и сравнение моделей:

Сравните свои результаты с теми, которые вы получили от линейной регрессии.

1. Какие метрики вы использовали для сравнения моделей? (Обоснуйте выбор: например, почему RMSE, а не MAE, или наоборот. Зачем нужен $R^2$?).
- r2 - кол-во объяснённой дисперсии (т.е. как хорошо модель в несоответствии с мат. ожиданием цены у выбранного объекта нашла, почему именно цена несовпадает). Для сравнения использовал MAE и MAPE (логичнее), но обучал по R2 (стабильнее для новых данных). Итог - модель лучше предсказывает цену в среднем (MAPE ниже: 8.86% linreg против 8.40% rf), причём предсказывает гораздо стабильнее (0.83 r2 на тесте у linreg против 0.9 у rf);

2. На какой части выборки вы считали метрики?
- на test само собой;

3. Какая модель по итогу справилась лучше?
rf > linreg:
Test  R²: 0.9050    Test  R²: 0.8386
Test  MAE: 820      Test  MAE: 904
Test  RMSE: 1126    Test  RMSE: 1467
Test  MAPE: 8.40%   Test  MAPE: 8.86%
Test MSE: 1267954   Test MSE: 2153391

4. Насколько хорошие получились результаты?
- лучше, чем linreg, однако можно лучше. Несмотря на это, средняя ошибка  MAPE подярка 8.5% и объяснённость дисперсии на уровне 90% - великолепный результат.