Линейная регрессия

1. Выбор датасета:

Выбор пал на предложенный авторами задания датасет - https://www.kaggle.com/datasets/vishakhdapat/price-of-used-toyota-corolla-cars

Его название - ToyotaCorolla.

Колонки выбранного датасета:
- Id (айдишка);
- Model (модель автомобиля);
- Price (цена (в будущем будет target));
- Age_08_04 (возраст автомобиля);
- Mfg_Month (месяц производства);
- Mfg_Year (год производства);
- KM (пробег автомобиля);
- Fuel_Type (вид топлива);
- HP (мощность автомобиля);
- Met_Color (металлик: 1 — да, 0 — нет);
- Color (цвет автомобиля);
- Automatic (АКПП: 1 — да, 0 — нет);
- CC (объем двигателя);
- Doors (количество дверей автомобиля);
- Cylinders (количество цилиндров двигателя автомобиля);
- Gears (количество передач КПП);
- Quarterly_Tax (налог на автомобиль);
- Weight (вес автомобиля);
- Mfr_Guarantee (гарантия от производителя: 1 — да, 0 — нет);
- BOVAG_Guarantee (гарантия BOVAG: 1 — да, 0 — нет);
- Guarantee_Period (срок гарантии);
- ABS (антиблокировочная система: 1 — есть, 0 — нет);
- Airbag_1 (подушка безопасности водителя: 1 — есть, 0 — нет);
- Airbag_2 (подушка безопасности пассажира: 1 — есть, 0 — нет);
- Airco (кондиционер: 1 — есть, 0 — нет);
- Automatic_airco (климат-контроль: 1 — есть, 0 — нет);
- Boardcomputer (бортовой компьютер: 1 — есть, 0 — нет);
- CD_Player (CD-плеер: 1 — есть, 0 — нет);
- Central_Lock (центральный замок: 1 — есть, 0 — нет);
- Powered_Windows (электростеклоподъемники: 1 — есть, 0 — нет);
- Power_Steering (усилитель руля: 1 — есть, 0 — нет);
- Radio (радио: 1 — есть, 0 — нет);
- Mistlamps (противотуманные фары: 1 — есть, 0 — нет);
- Sport_Model (спортивная комплектация: 1 — да, 0 — нет);
- Backseat_Divider (подлокотник задних сидений: 1 — есть, 0 — нет);
- Metallic_Rim (легкосплавные диски: 1 — есть, 0 — нет);
- Radio_cassette (радиокассетная магнитола: 1 — есть, 0 — нет);
- Parking_Assistant (парктроник: 1 — есть, 0 — нет);
- Tow_Bar (фаркоп: 1 — есть, 0 — нет);

Ох и много признаков тут... Аж целых 39... Надо будет делать меньше. Вряд ли наличие какого-нибудь фаркопа (что бы это не значило) так же сильно влияет на цену, как, например, возраст автомобиля или его мощность.

Я выбрал данный датасет, потому что:
- большое количество параметров - хорошо для Feature Engeneering-а (добавить, изменить, удалить признаки);
- около 1500 объектов - оптимально (всё ещё достаточно производительно, но результаты статистически будут гораздо точнее, чем в том же датасете Iris);
- машинки - это всегда круто, да и Ваня точно бы не посоветовал плохой датасет))

2. EDA и предобработка датасета ToyotaCorolla:

In [43]:
import pandas as pd
import numpy as np
import seaborn as sns
from plotly import express as px
sns.set_style('dark')

df = pd.read_csv('ToyotaCorolla.csv')

In [3]:
df.shape

(1436, 39)

In [6]:
df.head(1)

,Id,Model,Price,Age_08_04,Mfg_Month,Mfg_Year,KM,Fuel_Type,HP,Met_Color,...,Powered_Windows,Power_Steering,Radio,Mistlamps,Sport_Model,Backseat_Divider,Metallic_Rim,Radio_cassette,Parking_Assistant,Tow_Bar
0,1,TOYOTA Corolla 2.0 D4D HATCHB TERRA 2/3-Doors,13500,23,10,2002,46986,Diesel,90,1,...,1,1,0,0,0,1,0,0,0,0

In [7]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1436 entries, 0 to 1435
Data columns (total 39 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Id                 1436 non-null   int64
 1   Model              1436 non-null   str
 2   Price              1436 non-null   int64
 3   Age_08_04          1436 non-null   int64
 4   Mfg_Month          1436 non-null   int64
 5   Mfg_Year           1436 non-null   int64
 6   KM                 1436 non-null   int64
 7   Fuel_Type          1436 non-null   str
 8   HP                 1436 non-null   int64
 9   Met_Color          1436 non-null   int64
 10  Color              1436 non-null   str
 11  Automatic          1436 non-null   int64
 12  CC                 1436 non-null   int64
 13  Doors              1436 non-null   int64
 14  Cylinders          1436 non-null   int64
 15  Gears              1436 non-null   int64
 16  Quarterly_Tax      1436 non-null   int64
 17  Weight             1436 non-null   int64
 18  Mfr_Guarantee      1436 non-null   int64
 19  BOVAG_Guarantee    1436 non-null   int64
 20  Guarantee_Period   1436 non-null   int64
 21  ABS                1436 non-null   int64
 22  Airbag_1           1436 non-null   int64
 23  Airbag_2           1436 non-null   int64
 24  Airco              1436 non-null   int64
 25  Automatic_airco    1436 non-null   int64
 26  Boardcomputer      1436 non-null   int64
 27  CD_Player          1436 non-null   int64
 28  Central_Lock       1436 non-null   int64
 29  Powered_Windows    1436 non-null   int64
 30  Power_Steering     1436 non-null   int64
 31  Radio              1436 non-null   int64
 32  Mistlamps          1436 non-null   int64
 33  Sport_Model        1436 non-null   int64
 34  Backseat_Divider   1436 non-null   int64
 35  Metallic_Rim       1436 non-null   int64
 36  Radio_cassette     1436 non-null   int64
 37  Parking_Assistant  1436 non-null   int64
 38  Tow_Bar            1436 non-null   int64
dtypes: int64(36), str(3)
memory usage: 437.7 KB

Подметим, что в нашем датасете есть категориальные признаки, следовательно придётся применить Encoding. И, если в случае с цветом и типом топлива идеально подойдёт One-Hot Encoding, то вот с моделью автомобиля пока всё не так однозначно...

In [8]:
df.describe()

,Id,Price,Age_08_04,Mfg_Month,Mfg_Year,KM,HP,Met_Color,Automatic,CC,...,Powered_Windows,Power_Steering,Radio,Mistlamps,Sport_Model,Backseat_Divider,Metallic_Rim,Radio_cassette,Parking_Assistant,Tow_Bar
count,1436.000000,1436.000000,1436.000000,1436.000000,1436.000000,1436.000000,1436.000000,1436.000000,1436.000000,1436.00000,...,1436.000000,1436.000000,1436.000000,1436.000000,1436.000000,1436.000000,1436.000000,1436.000000,1436.000000,1436.000000
mean,721.555014,10730.824513,55.947075,5.548747,1999.625348,68533.259749,101.502089,0.674791,0.055710,1576.85585,...,0.561978,0.977716,0.146240,0.256964,0.300139,0.770195,0.204735,0.145543,0.002786,0.277855
std,416.476890,3626.964585,18.599988,3.354085,1.540722,37506.448872,14.981080,0.468616,0.229441,424.38677,...,0.496317,0.147657,0.353469,0.437111,0.458478,0.420854,0.403649,0.352770,0.052723,0.448098
min,1.000000,4350.000000,1.000000,1.000000,1998.000000,1.000000,69.000000,0.000000,0.000000,1300.00000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,361.750000,8450.000000,44.000000,3.000000,1998.000000,43000.000000,90.000000,0.000000,0.000000,1400.00000,...,0.000000,1.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000
50%,721.500000,9900.000000,61.000000,5.000000,1999.000000,63389.500000,110.000000,1.000000,0.000000,1600.00000,...,1.000000,1.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000
75%,1081.250000,11950.000000,70.000000,8.000000,2001.000000,87020.750000,110.000000,1.000000,0.000000,1600.00000,...,1.000000,1.000000,0.000000,1.000000,1.000000,1.000000,0.000000,0.000000,0.000000,1.000000
max,1442.000000,32500.000000,80.000000,12.000000,2004.000000,243000.000000,192.000000,1.000000,1.000000,16000.00000,...,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000

In [11]:
df.isnull().sum()

Id                   0
Model                0
Price                0
Age_08_04            0
Mfg_Month            0
Mfg_Year             0
KM                   0
Fuel_Type            0
HP                   0
Met_Color            0
Color                0
Automatic            0
CC                   0
Doors                0
Cylinders            0
Gears                0
Quarterly_Tax        0
Weight               0
Mfr_Guarantee        0
BOVAG_Guarantee      0
Guarantee_Period     0
ABS                  0
Airbag_1             0
Airbag_2             0
Airco                0
Automatic_airco      0
Boardcomputer        0
CD_Player            0
Central_Lock         0
Powered_Windows      0
Power_Steering       0
Radio                0
Mistlamps            0
Sport_Model          0
Backseat_Divider     0
Metallic_Rim         0
Radio_cassette       0
Parking_Assistant    0
Tow_Bar              0
dtype: int64

In [12]:
df.duplicated().sum()

np.int64(0)

И также посмотрим на моменты распределения (дисперсию, асимметрию и эксцесс):

In [13]:
df.select_dtypes(include=['int64', 'float64']).var()

Id                   1.734530e+05
Price                1.315487e+07
Age_08_04            3.459596e+02
Mfg_Month            1.124989e+01
Mfg_Year             2.373824e+00
KM                   1.406734e+09
HP                   2.244327e+02
Met_Color            2.196010e-01
Automatic            5.264333e-02
CC                   1.801041e+05
Doors                9.075927e-01
Cylinders            0.000000e+00
Gears                3.553619e-02
Quarterly_Tax        1.691563e+03
Weight               2.771088e+03
Mfr_Guarantee        2.419730e-01
BOVAG_Guarantee      9.361078e-02
Guarantee_Period     9.066270e+00
ABS                  1.519047e-01
Airbag_1             2.841226e-02
Airbag_2             2.004814e-01
Airco                2.501043e-01
Automatic_airco      5.326206e-02
Boardcomputer        2.079426e-01
CD_Player            1.709685e-01
Central_Lock         2.437564e-01
Powered_Windows      2.463303e-01
Power_Steering       2.180272e-02
Radio                1.249406e-01
Mistlamps            1.910665e-01
Sport_Model          2.102021e-01
Backseat_Divider     1.771180e-01
Metallic_Rim         1.629323e-01
Radio_cassette       1.244470e-01
Parking_Assistant    2.779692e-03
Tow_Bar              2.007915e-01
dtype: float64

In [14]:
df.select_dtypes(include=['int64', 'float64']).skew()

Id                    0.000789
Price                 1.703885
Age_08_04            -0.826702
Mfg_Month             0.290661
Mfg_Year              0.911304
KM                    1.015912
HP                    0.955836
Met_Color            -0.747029
Automatic             3.878197
CC                   27.431793
Doors                -0.076395
Cylinders             0.000000
Gears                 2.283960
Quarterly_Tax         1.993834
Weight                3.108639
Mfr_Guarantee         0.368588
BOVAG_Guarantee      -2.589204
Guarantee_Period      5.838435
ABS                  -1.610303
Airbag_1             -5.593385
Airbag_2             -0.996767
Airco                -0.033466
Automatic_airco       3.849562
Boardcomputer         0.902259
CD_Player             1.362712
Central_Lock         -0.324863
Powered_Windows      -0.250099
Power_Steering       -6.479621
Radio                 2.004439
Mistlamps             1.113561
Sport_Model           0.873060
Backseat_Divider     -1.285823
Metallic_Rim          1.465019
Radio_cassette        2.012363
Parking_Assistant    18.887772
Tow_Bar               0.992885
dtype: float64

In [15]:
df.select_dtypes(include=['int64', 'float64']).kurtosis()

Id                    -1.198935
Price                  3.737781
Age_08_04             -0.076632
Mfg_Month             -1.053692
Mfg_Year               0.070573
KM                     1.685057
HP                     8.836434
Met_Color             -1.443961
Automatic             13.058597
CC                   930.711227
Doors                 -1.874765
Cylinders              0.000000
Gears                 37.703476
Quarterly_Tax          4.298345
Weight                19.362901
Mfr_Guarantee         -1.866745
BOVAG_Guarantee        4.710535
Guarantee_Period      45.895434
ABS                    0.593902
Airbag_1              29.326794
Airbag_2              -1.007861
Airco                 -2.001670
Automatic_airco       12.837003
Boardcomputer         -1.187585
CD_Player             -0.143217
Central_Lock          -1.897108
Powered_Windows       -1.940155
Power_Steering        40.041251
Radio                  2.020588
Mistlamps             -0.761044
Sport_Model           -1.239494
Backseat_Divider      -0.347145
Metallic_Rim           0.146482
Radio_cassette         2.052462
Parking_Assistant    355.242681
Tow_Bar               -1.015596
dtype: float64

Перед рисованием графиков удалим ненужный в дальнейшем Id, дабы он не мозолил нам глаза:

In [44]:
df.drop('Id', axis=1, inplace=True)

Графики:

In [45]:
df_melted = df.select_dtypes(include=['int64', 'float64']).melt(var_name='Attribute', value_name='Value')
fig = px.box(
    df_melted,
    x='Attribute',
    y='Value',
    template='plotly_dark'
)

fig.show()

In [63]:
df_cols = df.select_dtypes(include=['int64', 'float64']).columns.to_list()
for i in df_cols:
    fig = px.histogram(
        df,
        x=i,
        y='Price',
        height=500,
        width=800,
        histfunc='avg',
        nbins=50
    )
    fig.update_layout(
        yaxis_title='Average price'
    )
    fig.update_traces(
        marker_line_color='black',
        marker_line_width=1.5
    )
    fig.show()

In [74]:
print(df_cols)
print(len(df_cols))
print(df.shape)

['Price', 'Age_08_04', 'Mfg_Month', 'Mfg_Year', 'KM', 'HP', 'Met_Color', 'Automatic', 'CC', 'Doors', 'Cylinders', 'Gears', 'Quarterly_Tax', 'Weight', 'Mfr_Guarantee', 'BOVAG_Guarantee', 'Guarantee_Period', 'ABS', 'Airbag_1', 'Airbag_2', 'Airco', 'Automatic_airco', 'Boardcomputer', 'CD_Player', 'Central_Lock', 'Powered_Windows', 'Power_Steering', 'Radio', 'Mistlamps', 'Sport_Model', 'Backseat_Divider', 'Metallic_Rim', 'Radio_cassette', 'Parking_Assistant', 'Tow_Bar']
35
(1436, 38)

Так как у всех автомобилей 4 цилиндра, сходу уберём и этот, абсолютно бесполезный, признак:

In [75]:
df.drop('Cylinders',axis=1 ,inplace=True)

In [76]:
fig = px.scatter(
    df,
    x='KM',
    y='Price',
    title=f'{i} vs Price (average)',
)
fig.update_layout(
    yaxis_title='Price'
)
fig.update_traces(
    marker_line_color='black',
    marker_line_width=0.5,
    opacity=0.6
)
fig.update_traces(
    marker_line_color='black',
    marker_line_width=0.5
)
fig.show()